name: xstream
description: A Cutting-Edge Network Accelerator Powered by XTLS VLESS.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  process_run: ^0.12.0 # 添加 process_run 依赖

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # 注册外部资源
  assets:
    - assets/xray-template.json
