name: xstream
description: A cross-platform network accelerator powered by XTLS VLESS.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  http: ^1.4.0
  path_provider: ^2.1.5
  process_run: 1.1.0
  ffi: 2.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_lints: 4.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  json_annotation: ^4.4.0
  flutter_launcher_icons: ^0.14.3  # ✅ 升级：解决唯一一个受限 direct dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.0.1
  msix: ^3.9.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
