name: Build and Release Flutter Packages

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, windows, macos, android, ios]
        arch: [x64, arm64]
        exclude:
          - platform: linux
            arch: arm64
          - platform: windows
            arch: arm64
          - platform: ios
            arch: x64
          - platform: android
            arch: x64
        include:
          - platform: macos
            arch: x64
          - platform: macos
            arch: arm64
          - platform: linux
            arch: x64
          - platform: android
            arch: arm64
          - platform: ios
            arch: arm64
          - platform: windows
            arch: x64

    runs-on: ${{ matrix.platform == 'windows' && 'windows-latest' ||
                 matrix.platform == 'linux'   && 'ubuntu-latest' ||
                 matrix.platform == 'android' && 'ubuntu-latest' ||
                 matrix.platform == 'macos'   && 'macos-latest' ||
                 matrix.platform == 'ios'     && 'macos-latest' }}

    env:
      PLATFORM: ${{ matrix.platform }}
      ARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Flutter (Unix)
        if: ${{ matrix.platform != 'windows' }}
        shell: bash
        run: |
          echo "🔧 Setting up Flutter for $PLATFORM ($ARCH)"
          if [[ "$PLATFORM" == "linux" ]]; then
            sudo apt-get update
            sudo snap install flutter --classic
            sudo apt-get install -y clang cmake ninja-build libgtk-3-dev pkg-config libx11-dev binutils
            export PATH="$PATH:/snap/bin"
            as --version
          elif [[ "$PLATFORM" == "android" ]]; then
            sudo apt-get update
            sudo snap install flutter --classic
            export PATH="$PATH:/snap/bin"
            sudo apt-get install -y openjdk-17-jdk
            JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
            echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
            sudo update-alternatives --set java $JAVA_HOME/bin/java
            sudo update-alternatives --set javac $JAVA_HOME/bin/javac
            java -version
          elif [[ "$PLATFORM" == "macos" || "$PLATFORM" == "ios" ]]; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            if [[ "$ARCH" == "arm64" ]]; then
              eval "$(/opt/homebrew/bin/brew shellenv)"
            else
              eval "$(/usr/local/bin/brew shellenv)"
            fi
            brew install --cask flutter
            export PATH="$PATH:$HOME/Library/Flutter/bin"
          fi
          flutter doctor

      - name: Set up Flutter (Windows)
        if: ${{ matrix.platform == 'windows' }}
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.2'

      - name: Show Flutter version
        shell: bash
        run: flutter --version

      - name: Run Flutter tests (Linux only)
        if: ${{ matrix.platform == 'linux' && matrix.arch == 'x64' }}
        run: flutter test --reporter expanded

      - name: Generate launcher icons (Android)
        if: ${{ matrix.platform == 'android' }}
        run: |
          flutter pub get
          dart run flutter_launcher_icons

      - name: Set up Go (Linux only)
        if: ${{ matrix.platform == 'linux' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Flutter app (Linux)
        if: ${{ matrix.platform == 'linux' }}
        shell: bash
        run: |
          flutter clean
          flutter pub get
          flutter pub outdated --show-all
          flutter build linux --release -v

      - name: Build Flutter app (macOS)
        if: ${{ matrix.platform == 'macos' }}
        run: flutter build macos --release

      - name: Build Flutter app (iOS)
        if: ${{ matrix.platform == 'ios' }}
        run: flutter build ios --release --no-codesign

      - name: Build Flutter app (Android)
        if: ${{ matrix.platform == 'android' }}
        run: flutter build apk --release

      - name: Build Flutter app (Windows)
        if: ${{ matrix.platform == 'windows' }}
        shell: powershell
        run: |
          flutter pub get
          flutter build windows --release
          if (-not (Test-Path "windows/flutter/generated_plugin_registrant.h")) {
            Write-Host "❌ Plugin registrant header missing!"
            exit 1
          }

      - name: Create DMG package (macOS)
        if: ${{ matrix.platform == 'macos' }}
        run: |
          brew install create-dmg
          DMG_NAME="XStream-${ARCH}.dmg"
          echo "💽 Creating macOS DMG: $DMG_NAME"
          create-dmg \
            --volname "XStream Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            build/macos/$DMG_NAME \
            build/macos/Build/Products/Release/xstream.app

      - name: Zip iOS Runner.app
        if: ${{ matrix.platform == 'ios' }}
        run: |
          cd build/ios/iphoneos
          zip -r XStream.app.zip Runner.app

      - name: Show distributable build output
        shell: bash
        run: |
          echo "🎯 Distributable output for $PLATFORM-$ARCH:"
          if [[ "$PLATFORM" == "linux" ]]; then
            find build/linux -type f -executable -exec file {} \; | grep ELF | cut -d: -f1 | tee /tmp/${PLATFORM}-${ARCH}-release.log
          else
            find build -type f \( -iname "*.apk" -o -iname "*.dmg" -o -iname "*.exe" -o -iname "*.aab" -o -iname "*.app" \) | tee /tmp/${PLATFORM}-${ARCH}-release.log
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            build/macos/*.dmg
            build/linux/x64/release/bundle/xstream
            build/windows/x64/runner/Release/xstream.exe
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/iphoneos/XStream.app.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List all downloaded artifacts
        run: |
          echo "🎯 Listing contents of release-artifacts"
          find release-artifacts -type f | tee /tmp/artifacts.list
          echo "📦 Artifact summary:"
          cat /tmp/artifacts.list

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: daily-${{ github.run_number }}
          name: Daily Build ${{ github.run_number }}
          files: |
            release-artifacts/**/*.dmg
            release-artifacts/**/xstream.exe
            release-artifacts/**/app-release.apk
            release-artifacts/**/XStream.app.zip
            release-artifacts/build-linux-x64/linux/x64/release/bundle/xstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
