name: Build and Release Flutter Packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, windows, macos, android, ios]
        arch: [x64, arm64]
        exclude:
          - platform: windows
            arch: arm64
          - platform: ios
            arch: x64
          - platform: android
            arch: x64
        include:
          - platform: macos
            arch: x64
          - platform: macos
            arch: arm64
          - platform: linux
            arch: x64
          - platform: linux
            arch: arm64
          - platform: android
            arch: arm64
          - platform: ios
            arch: arm64
          - platform: windows
            arch: x64

    runs-on: ${{ matrix.platform == 'windows' && 'windows-latest' ||
                 matrix.platform == 'linux'   && 'ubuntu-latest' ||
                 matrix.platform == 'android' && 'ubuntu-latest' ||
                 matrix.platform == 'macos'   && 'macos-latest' ||
                 matrix.platform == 'ios'     && 'macos-latest' }}

    env:
      PLATFORM: ${{ matrix.platform }}
      ARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter for Unix-like Platforms
        if: ${{ matrix.platform != 'windows' }}
        shell: bash
        run: |
          echo "Setting up Flutter for $PLATFORM ($ARCH)"

          if [[ "$PLATFORM" == "linux" ]]; then
            sudo apt-get update
            sudo snap install flutter --classic
            export PATH="$PATH:/snap/bin"

          elif [[ "$PLATFORM" == "android" ]]; then
            sudo apt-get update
            sudo snap install flutter --classic
            sudo apt-get install -y openjdk-17-jdk
            JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
            echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
            sudo update-alternatives --set java $JAVA_HOME/bin/java
            sudo update-alternatives --set javac $JAVA_HOME/bin/javac
            export PATH="$PATH:/snap/bin"
            java -version

          elif [[ "$PLATFORM" == "macos" || "$PLATFORM" == "ios" ]]; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            if [[ "$ARCH" == "arm64" ]]; then
              eval "$(/opt/homebrew/bin/brew shellenv)"
            else
              eval "$(/usr/local/bin/brew shellenv)"
            fi
            brew install --cask flutter
            export PATH="$PATH:$HOME/Library/Flutter/bin"
          fi

          flutter doctor

      - name: Set up Flutter for Windows
        if: ${{ matrix.platform == 'windows' }}
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install flutter -y
          echo "C:\tools\flutter\bin" | Out-File -Append -FilePath $env:GITHUB_PATH
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
          flutter --version

      - name: Run Make Build
        if: ${{ matrix.platform != 'windows' }}
        shell: bash
        run: |
          make $PLATFORM-$ARCH

      - name: Show Distributable output
        shell: bash
        run: |
          echo "🎯 Distributable output for $PLATFORM-$ARCH:"
          if [[ "$PLATFORM" == "linux" ]]; then
              find build/linux -type f -executable -exec file {} \; | grep ELF | cut -d: -f1 | tee /tmp/${{ matrix.platform }}-${{ matrix.arch }}-release.log
          else
              find build -type f \( -iname "*.apk" -o -iname "*.dmg" -o -iname "*.exe" -o -iname "*.aab" -o -iname "*.app" \) | tee /tmp/${{ matrix.platform }}-${{ matrix.arch }}-release.log
          fi

      - name: Upload filtered artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            build/macos/XStream-${{ matrix.arch }}.dmg
            build/linux/x64/release/bundle/xstream-x64
            build/linux/arm64/release/bundle/xstream-arm64
            build/windows/x64/runner/Release/xstream.exe
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/apk/release/app-release.apk
            build/app/outputs/bundle/release/*.aab
            build/ios/iphoneos/xstream.app.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List all downloaded artifacts
        run: find release-artifacts -type f

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: daily-${{ github.run_number }}
          name: Daily Build ${{ github.run_number }}
          files: |
            release-artifacts/**/xstream-*
            release-artifacts/**/xstream.exe
            release-artifacts/**/app-release.apk
            release-artifacts/**/xstream.app.zip
            release-artifacts/**/XStream-*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
