name: Code Analysis

# 触发条件：在 PR 请求到 'main' 分支时运行
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      # 检查敏感信息
      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          sudo make install -C git-secrets
          git secrets --install
          git secrets --scan

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.2'

      # 运行 Flutter 的静态分析
      - name: Run flutter analyze
        run: |
          flutter analyze

