name: Code Analysis

# 触发条件：在 PR 请求到 'main' 分支时运行
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Install Flutter
        run: |
          sudo apt-get update
          sudo snap install flutter --classic
          export PATH="$PATH:/snap/bin"
          flutter doctor

      # 运行 Flutter 的静态分析
      - name: Run flutter analyze
        run: |
          flutter analyze

      # 可选：使用 git-secrets 检查敏感信息
      - name: Install git-secrets (optional, for sensitive info checks)
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          sudo make install -C git-secrets
          git secrets --install
          git secrets --scan
